version: '3.8'

services:
  ollama:
    volumes:
      - $HOME/ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 12345:12345
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    volumes:
      - $HOME/ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8000:8080
    environment:
      - '/ollama/api=http://ollama:12345/api'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped